#!/usr/bin/env bash
OPTIONS_SPEC='git encrypt --install
git encrypt --configure
git encrypt --add-pattern <pattern>
--
install Installs filter scripts.
configure Configure aws and kms settings.
add-pattern Adds pattern for encryption file.'

# Include the git setup script. This parses and normalized CLI arguments.
. $(git --exec-path)/git-sh-setup

[ -z $GIT_DIR ] && GIT_DIR="$(git rev-parse --git-dir)"
GIT_PROJECT_TOP_LEVEL="$(git rev-parse --show-toplevel)"

function add_attribute() {
  local attribute="$1" file="$2"
  [ -z "$file" ] && file="$GIT_PROJECT_TOP_LEVEL/.gitattributes"
  [ ! -f "$file" ] && touch "$file"
  grep "$attribute" "$file" >/dev/null 2>&1
  [ "0" == "$?" ] || echo "$attribute" >> "$file"
}

function die() {
  exit 1
}

function ask_config() {
  local key="$1" default="$2" message="$3"
  configured=$(git config --get "$key")
  [ -z $configured ] && configured="$default"
  echo -n "Input $message [$configured]:"
  read input
  [ -z "$input" ] && input=$configured
  git config --replace-all "$key" "$input"
}

function generate_encryption_key() {
  local profile=$(git config --get encrypt.aws.profile)
    region=$(git config --get encrypt.aws.region)
    key=$(git config --get encrypt.kms.key-id)
    data_key_file="$GIT_PROJECT_TOP_LEVEL/.gitdatakey"
  [ -f "$data_key_file" ] && return
  [ -n "$profile" ] && profile="--profile '$profile'"
  [ -n "$region" ] && region="--region '$region'"
  aws kms generate-data-key-without-plaintext \
    $profile \
    $region \
    --key-id "$key" \
    --key-spec AES_256 \
    --query CiphertextBlob \
    --output text | base64 --decode > $data_key_file || die
}

function decrypted_data_key() {
  local profile=$(git config --get encrypt.aws.profile)
    region=$(git config --get encrypt.aws.region)
    file="$GIT_PROJECT_TOP_LEVEL/.gitdatakey"
    profile="$(git config --get encrypt.kms.profile)"
  [ -n $profile ] && profile="--profile '$profile'"
  [ -n $region ] && region="--region '$region'"
  aws kms decrypt \
    $profile \
    $region \
    --ciphertext-blob "fileb://${file}" \
    --query Plaintext
    --output text
}

function install() {
  git config --replace-all merge.renormalize true
  git config --replace-all filter.git-encrypt.clean  "git-encrypt --clean"
  git config --replace-all filter.git-encrypt.smudge "git-encrypt --smudge"
  git config --replace-all diff.git-encrypt.textconv "git-encrypt --diff"
  add_attribute ".git* !filter !diff" $GIT_DIR/info/attributes
  configure
  generate_encryption_key
}

function configure() {
  ask_config "encrypt.aws.profile" "" "your aws profile"
  ask_config "encrypt.aws.region"  "" "region to use"
  ask_config "encrypt.kms.key-id"  "" "Specified key for AWS KMS"
}

function add_filter_pattern() {
  local pattern="$1"
  add_attribute "$pattern filter=git-encrypt diff=git-encrypt"
}

function clean() {
  local pass="pass:$(decrypted_data_key)"
        data="$(cat -)"
        salt="$(echo -n $data | sha1sum | head -c 16)"
  echo -n $data | openssl enc -base64 -aes-256-cbc -pass $pass -S $salt
}

function smudge() {
  local pass="pass:$(decrypted_data_key)"
        data="$(cat -)"
  echo -n $data | openssl enc -d -base64 -aes-256-cbc -pass $pass 2>/dev/null || echo -n $data
}

function diff() {
  local pass="pass:$(decrypted_data_key)"
  openssl enc -d -base64 -aes-256-cbc -pass $pass -in "$1" 2>/dev/null || cat "$1"
}

declare COMMAND="$1"
shift 1

case "$COMMAND" in
  --) "$0" -h; exit 0 ;;
  --install) install ;;
  --configure) configure ;;
  --add-pattern) add_filter_pattern "$1" ;;
  --list-patterns) list_filter_patterns ;;
  --clean) clean ;;
  --smudge) smudge ;;
  --diff) diff "$1" ;;
  *) echo "Unknown option: ${option}"; "$0" -h; exit 1;;
esac

